# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddLeaseDialog(object):
    def setupUi(self, AddLeaseDialog):
        AddLeaseDialog.setObjectName("AddLeaseDialog")
        AddLeaseDialog.resize(420, 500)
        self.vboxlayout = QtWidgets.QVBoxLayout(AddLeaseDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.formlayout = QtWidgets.QFormLayout()
        self.formlayout.setObjectName("formlayout")
        self.label = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label.setObjectName("label")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.branchInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.branchInput.setObjectName("branchInput")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.branchInput)
        self.label1 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label1.setObjectName("label1")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label1)
        self.headInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.headInput.setObjectName("headInput")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.headInput)
        self.label2 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label2.setObjectName("label2")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label2)
        self.contactInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.contactInput.setPlaceholderText("")
        self.contactInput.setObjectName("contactInput")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.contactInput)
        self.label3 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label3.setObjectName("label3")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label3)
        self.dateReceivedInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.dateReceivedInput.setCalendarPopup(True)
        self.dateReceivedInput.setObjectName("dateReceivedInput")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateReceivedInput)
        self.label4 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label4.setObjectName("label4")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label4)
        self.termInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.termInput.setObjectName("termInput")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.termInput)
        self.label5 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label5.setObjectName("label5")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label5)
        self.fromDateInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.fromDateInput.setCalendarPopup(True)
        self.fromDateInput.setObjectName("fromDateInput")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fromDateInput)
        self.label6 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label6.setObjectName("label6")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label6)
        self.toDateInput = QtWidgets.QDateEdit(parent=AddLeaseDialog)
        self.toDateInput.setCalendarPopup(True)
        self.toDateInput.setObjectName("toDateInput")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.toDateInput)
        self.label7 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label7.setObjectName("label7")
        self.formlayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label7)
        self.floorAreaInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.floorAreaInput.setObjectName("floorAreaInput")
        self.formlayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.floorAreaInput)
        self.label8 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label8.setObjectName("label8")
        self.formlayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label8)
        self.memoInput = QtWidgets.QLineEdit(parent=AddLeaseDialog)
        self.memoInput.setObjectName("memoInput")
        self.formlayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.memoInput)
        self.label9 = QtWidgets.QLabel(parent=AddLeaseDialog)
        self.label9.setObjectName("label9")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label9)
        self.remarksInput = QtWidgets.QTextEdit(parent=AddLeaseDialog)
        self.remarksInput.setObjectName("remarksInput")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.remarksInput)
        self.vboxlayout.addLayout(self.formlayout)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(parent=AddLeaseDialog)
        self.saveButton.setObjectName("saveButton")
        self.hboxlayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddLeaseDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(AddLeaseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddLeaseDialog)

    def retranslateUi(self, AddLeaseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddLeaseDialog.setWindowTitle(_translate("AddLeaseDialog", "Add Lease"))
        self.label.setText(_translate("AddLeaseDialog", "Branch:"))
        self.label1.setText(_translate("AddLeaseDialog", "Head:"))
        self.label2.setText(_translate("AddLeaseDialog", "Contact Number:"))
        self.label3.setText(_translate("AddLeaseDialog", "Date Received:"))
        self.label4.setText(_translate("AddLeaseDialog", "Term:"))
        self.label5.setText(_translate("AddLeaseDialog", "From:"))
        self.label6.setText(_translate("AddLeaseDialog", "To:"))
        self.label7.setText(_translate("AddLeaseDialog", "Floor Area:"))
        self.label8.setText(_translate("AddLeaseDialog", "Memo Number:"))
        self.label9.setText(_translate("AddLeaseDialog", "Remarks:"))
        self.saveButton.setText(_translate("AddLeaseDialog", "Save"))
        self.cancelButton.setText(_translate("AddLeaseDialog", "Cancel"))


class AddBranchDialog(QtWidgets.QDialog):
    """Adapter dialog used by Contract Expiry to collect a new branch row."""

    def __init__(self, headers=None, values=None, parent=None):
        super().__init__(parent)
        self.ui = Ui_AddLeaseDialog()
        self.ui.setupUi(self)

        self._values = list(values or [])
        if len(self._values) < 12:
            self._values.extend([""] * (12 - len(self._values)))

        self._apply_initial_values()

        self.ui.saveButton.clicked.connect(self.accept)
        self.ui.cancelButton.clicked.connect(self.reject)

    def _parse_date(self, value):
        text = str(value or "").strip()
        if not text:
            return None
        for fmt in ("dd-MMM-yy", "d-MMM-yy", "yyyy-MM-dd", "dd/MM/yyyy", "MM/dd/yyyy"):
            parsed = QtCore.QDate.fromString(text, fmt)
            if parsed.isValid():
                return parsed
        return None

    def _set_date_edit(self, date_edit, value):
        parsed = self._parse_date(value)
        if parsed is not None:
            date_edit.setDate(parsed)

    def _apply_initial_values(self):
        self.ui.branchInput.setText(self._values[0])
        self._set_date_edit(self.ui.dateReceivedInput, self._values[1])
        self.ui.termInput.setText(self._values[3])
        self.ui.headInput.setText(self._values[4])
        self.ui.contactInput.setText(self._values[5])
        self._set_date_edit(self.ui.fromDateInput, self._values[6])
        self._set_date_edit(self.ui.toDateInput, self._values[7])
        self.ui.floorAreaInput.setText(self._values[8])
        self.ui.memoInput.setText(self._values[9])
        self.ui.remarksInput.setPlainText(self._values[11])

        for field in (self.ui.dateReceivedInput, self.ui.fromDateInput, self.ui.toDateInput):
            field.setDisplayFormat("dd-MMM-yy")
            field.setCalendarPopup(True)

    def values(self):
        # Matches Contract Expiry UI row layout (12 columns, Reminder removed).
        return [
            self.ui.branchInput.text().strip(),
            self.ui.dateReceivedInput.date().toString("dd-MMM-yy"),
            "",  # DATE SENT TO HO is not present in this generated UI.
            self.ui.termInput.text().strip(),
            self.ui.headInput.text().strip(),
            self.ui.contactInput.text().strip(),
            self.ui.fromDateInput.date().toString("dd-MMM-yy"),
            self.ui.toDateInput.date().toString("dd-MMM-yy"),
            self.ui.floorAreaInput.text().strip(),
            self.ui.memoInput.text().strip(),
            "",  # DATE COMPLETED/SENT is not present in this generated UI.
            self.ui.remarksInput.toPlainText().strip(),
        ]


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddLeaseDialog = QtWidgets.QDialog()
    ui = Ui_AddLeaseDialog()
    ui.setupUi(AddLeaseDialog)
    AddLeaseDialog.show()
    sys.exit(app.exec())
